"""empty message

Revision ID: bb8cdee72f17
Revises: 2d67a5758487
Create Date: 2025-03-03 11:00:09.375751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8cdee72f17'
down_revision = '2d67a5758487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))

    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batting_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rbi', sa.Integer(), nullable=True))
        batch_op.alter_column('num_pitches',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('num_strikeouts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.alter_column('num_strikeouts',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('num_pitches',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('rbi')
        batch_op.drop_column('batting_avg')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
